version: '3.9'

services:
  db:
    container_name: db_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: db_travel
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: db_travel
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  golang:
    image: golang:1.21
    container_name: golang
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh 
    ports:
      - "8080:8080"
    command: "go run main.go"
    depends_on:
      - db
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Baixar o script wait-for-it
        curl -sSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o /workspace/wait-for-it.sh
        chmod +x /workspace/wait-for-it.sh
        
        # Esperar o banco de dados estar disponível na porta 5432 (máximo de 10 tentativas)
        /workspace/wait-for-it.sh db:5432 --timeout=300 -- go run main.go
